general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot # Paņem tavu pašreizējo ekrānu
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3 # Jo vairāk passes, jo stiprāks blur
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vignette = 0.1
    vignette_thickness = 0.3
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 242, 255, 0.8) # Neon zils
    inner_color = rgba(30, 30, 30, 0.5) # Caurspīdīgs tumšs
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <span foreground="##00f2ff">Enter Password...</span>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(0, 242, 255, 1.0) # Neon zils pulkstenis
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}
