# --- Caurspīdīgums ---
background_opacity 0.85

# --- Dinamiskā kontrole ---
# Šis ļauj Pywal mainīt krāsas, neaizverot termināli
allow_remote_control yes
listen_on unix:/tmp/kitty

# --- Pywal Integrācija ---
# Šī rinda ir vissvarīgākā - tā ielādē krāsas, ko Pywal izvelk no fona bildes
include ~/.cache/wal/colors-kitty.conf

# --- Atlases krāsa (Pēc izvēles, ja gribi savu) ---
selection_background  #665482
selection_foreground  #ffffff
